
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=1  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=2  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=3  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=4  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=5  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=6  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=7  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=8  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=9  --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=10 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=11 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=12 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=13 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=14 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=15 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=2 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=16 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=17 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=18 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=19 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=20 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=21 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=22 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=23 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=24 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=25 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=26 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=27 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=28 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=29 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks &&
python3 train_search.py --population_size=32 --epochs=30 --gpu=1 --seed=30 --num_intermediate_nodes=2 --concat=2 --w_inertia=0.5 --start_using_pso=5 --c_local=1 --gpu=1 --use_blocks
